In [2]:
import numpy as np

In [3]:
ary_1 = np.array([1,2,3,4,5])
print(ary_1)

[1 2 3 4 5]


### 2D array

In [4]:
ary_2 = np.array([[1,2,3],[4,5,6]])
print(ary_2)

[[1 2 3]
 [4 5 6]]


In [5]:
print(ary_2.shape) 
print(aray_2.size) # Output: (2, 3)

(2, 3)


NameError: name 'aray_2' is not defined

In [ ]:
print(aray_2[0,1])

In [ ]:
aray_2[1,2] = 9
print(aray_2)


[[ 1 99  3]
 [ 4  5  9]]


### Multiplications

### list muultiplications:

In [ ]:
lst_1 = [1,3,9]
print(lst_1 * 3) # Output: [1, 3, 9, 1, 3, 9, 1, 3, 9]

[1, 3, 9, 1, 3, 9, 1, 3, 9]


### array multiplications

In [ ]:
m_aray = np.array([1,3,9])
print(m_aray * 3) # Output: [ 3  9 27]

[ 3  9 27]


## practice for elment wise multiplication

In [ ]:
data_list =[i*2 for i in range(1000000)]

### Numpy Methods

In [7]:
m_ary_1 = np.zeros([2,3])
print(m_ary_1)

[[0. 0. 0.]
 [0. 0. 0.]]
